name: Attach Artifact to Release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
  
permissions:
  contents: write
  actions: read
  packages: write
  id-token: write  
jobs:
  attach-artifact-to-release:
    uses: liquibase/build-logic/.github/workflows/extension-attach-artifact-release.yml@fix/DAT-20612-simple-gpg-masking
    secrets: inherit

