# This workflow will build the extension against the latest Liquibase artifact
name: "Nightly build"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1-5"

permissions:
  contents: write
  pull-requests: write
  packages: read
  id-token: write # Required for OIDC authentication

jobs:
  nightly-build:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    with:
      nightly: true
    secrets: inherit

  night-build-e2e:
    needs: nightly-build
    name: Java ${{ matrix.java }} | Neo4j ${{ matrix.neo4j_version }} (EE? ${{ matrix.enterprise }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21, 25]
        neo4j_version:
          - "4.4"
          - "5.26"
          - "2026.03"
        enterprise:
          - "true"
          - "false"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
          cache: "maven"

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@2cb1a461cbd4865ac4299648312e4704c646cd53 # v3.0.1
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      # look for dependencies in maven
      - name: Set up Maven settings.xml
        uses: liquibase/build-logic/.github/actions/setup-maven-settings@dcd3f78de006c4ca2348b462794c8a236adcb311 # main
        with:
          gpm-token: ${{ env.LIQUIBOT_PAT_GPM_ACCESS }}

      - name: Run Tests
        run: mvn --quiet --show-version --batch-mode verify -Dliquibase.version="master-SNAPSHOT" -Djava.version=${{ matrix.java }}
        env:
          NEO4J_VERSION: ${{ matrix.neo4j_version }}
          ENTERPRISE: ${{ matrix.enterprise }}
