name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  issues: read
  statuses: read
  actions: read
  security-events: write
  id-token: write # Required by AWS OIDC authentication in sonar

jobs:
  create-release:
    uses: liquibase/build-logic/.github/workflows/create-release.yml@main
    secrets: inherit

