name: Publish docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'documentation.Dockerfile'
      - 'documentation.dockerignore'
      - 'mkdocs.yml'
      - 'docs/**'
      - 'src/test/resources/e2e/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Build
        run: |
          docker build --file documentation.Dockerfile --tag liquibase/neo4j-docs:latest .
          docker run --pull never --volume "$(pwd)":/usr/src/app liquibase/neo4j-docs:latest build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@acca2b1b2070338fb9fd1ca27ecee81d687e58e5 # v6.1.2
        with:
          aws-access-key-id: ${{ secrets.NEO4J_DOCS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEO4J_DOCS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.NEO4J_DOCS_S3_REGION }}

      - name: Sync to Static
        env:
          AWS_S3_BUCKET: ${{ secrets.NEO4J_DOCS_S3_BUCKET }}
        run: |
          aws s3 sync site/ "s3://${AWS_S3_BUCKET}/labs/liquibase/docs" --acl public-read --follow-symlinks
