name: Publish docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'documentation.Dockerfile'
      - 'documentation.dockerignore'
      - 'mkdocs.yml'
      - 'docs/**'
      - 'src/test/resources/e2e/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Build
        run: |
          docker build --file documentation.Dockerfile --tag liquibase/neo4j-docs:latest .
          docker run --pull never --volume "$(pwd)":/usr/src/app liquibase/neo4j-docs:latest build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          aws-access-key-id: ${{ secrets.NEO4J_DOCS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEO4J_DOCS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.NEO4J_DOCS_S3_REGION }}

      - name: Sync to Static
        env:
          AWS_S3_BUCKET: ${{ secrets.NEO4J_DOCS_S3_BUCKET }}
        run: |
          aws s3 sync site/ "s3://${AWS_S3_BUCKET}/labs/liquibase/docs" --acl public-read --follow-symlinks
