name: Build and Test with 5.x Neo4j Java driver

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - "documentation.Dockerfile"
      - "documentation.dockerignore"
      - "mkdocs.yml"
      - "docs/**"

permissions:
  contents: write
  pull-requests: write
  packages: read
  id-token: write # Required for OIDC authentication

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build-test:
    needs: authorize
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    secrets: inherit

  integration-test:
    needs: build-test
    name: Java ${{ matrix.java }} | Neo4j ${{ matrix.neo4j_version }} (EE? ${{ matrix.enterprise }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]
        neo4j_version:
          - "4.4"
          - "5"
          - "2025.01"
        enterprise:
          - "true"
          - "false"

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
          cache: "maven"

      - name: Run Tests
        run: mvn -P5x-driver --quiet --show-version --batch-mode verify
        env:
          NEO4J_VERSION: ${{ matrix.neo4j_version }}
          ENTERPRISE: ${{ matrix.enterprise }}
