name: Build and Test with 5.x Neo4j Java driver

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - 'documentation.Dockerfile'
      - 'documentation.dockerignore'
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@v0.7.3
    secrets: inherit

  integration-test:
    needs: build-test
    name: Java ${{ matrix.java }} | Neo4j ${{ matrix.neo4j_version }} (EE? ${{ matrix.enterprise }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]
        neo4j_version:
          - "4.4"
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"
          - "5.7"
          - "5.8"
          - "5.9"
          - "5.10"
          - "5.11"
          - "5.12"
          - "5.13"
          - "5.14"
          - "5.15"
          - "5.16"
          - "5.17"
          - "5.18"
        enterprise:
          - "true"
          - "false"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests
        run: mvn -P5x-driver --quiet --show-version --batch-mode verify
        env:
          NEO4J_VERSION: ${{ matrix.neo4j_version }}
          ENTERPRISE: ${{ matrix.enterprise }}
