name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - "documentation.Dockerfile"
      - "documentation.dockerignore"
      - "mkdocs.yml"
      - "docs/**"

permissions:
  contents: read
  pull-requests: write
  packages: read
  id-token: write # Required for OIDC authentication

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    secrets: inherit
